/usr/bin/env: ‘python’: No such file or directory
/usr/bin/env: ‘python’: No such file or directory
Traceback (most recent call last):
  File "/home/iko4ak/courses_works/distribution/manage.py", line 22, in <module>
    main()
  File "/home/iko4ak/courses_works/distribution/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/iko4ak/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/iko4ak/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/home/iko4ak/.local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/iko4ak/.local/lib/python3.10/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/home/iko4ak/.local/lib/python3.10/site-packages/django/apps/config.py", line 193, in create
    import_module(entry)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django_crontab'
